import pynndescent
from hdimvis.algorithms.BaseAlgorithm import BaseAlgorithm
from hdimvis.algorithms.spring_force_algos.Node import Node
from hdimvis.algorithms.spring_force_algos.utils import jiggle, get_size, mean
from ...data_fetchers.Dataset import Dataset
from itertools import combinations
from typing import Tuple, List, Dict, FrozenSet
from abc import abstractmethod
import numpy as np
import math

# code adapted and modified from 2019 Project by Iain Cattermole

class SpringForceBase(BaseAlgorithm):

    available_metrics = ['Stress', 'Average speed']

    def __init__(self, dataset: Dataset | None, nodes: List[Node] = None, enable_cache: bool = True,
                 alpha: float = 1, use_knnd: bool = False, knnd_parameters: Dict = None,
                 neighbour_set_size: int = 5, sample_set_size: int = 10, **kwargs) -> None:
        # the base class extracts data from the Dataset object
        super().__init__(dataset, **kwargs)

        assert neighbour_set_size > 0 or sample_set_size > 0, "Sample set and Neighbour set cannot be both zero"

        self.nodes: List[Node] = nodes if nodes is not None else self.build_nodes()
        self.data_size_factor: float = 1
        self.neighbour_set_size: int = neighbour_set_size
        self.sample_set_size:    int = sample_set_size
        self._average_speeds: List[float] = list()
        self.enable_cache: bool = enable_cache
        self.alpha = alpha
        self.knnd_parameters = knnd_parameters
        self.use_knnd = use_knnd
        if self.use_knnd:
            if self.data is not None:
                self.knnd_index = self.create_knnd_index()
            else:
                self.knnd_index = None

        if enable_cache:
            self.distances: Dict[FrozenSet[Node], float] = dict()
        else:
            # Change the distance function
            self.distance = self.distance_no_cache

    @abstractmethod
    def one_iteration(self, *args, **kwargs) -> None:
        """
        Perform one iteration of the algorithm
        """
        pass

    def build_nodes(self) -> List[Node] | None:
        """
        Construct a Node for each datapoint
        """
        if self.data is not None:
            # concatenate the datapoints with the initial positions for low-d mappings
            # for the apply_along_axis fn
            conc = np.concatenate((self.data, self.initial_layout), axis=1)
            return list(np.apply_along_axis(Node, axis=1, arr=conc))
        else:
            return None

    def get_positions(self) -> np.ndarray:
        return np.array([(n.x, n.y) for n in self.nodes])

    # def get_available_metrics(self):
    #     return self._available_metrics

    def set_positions(self, positions: np.ndarray) -> None:
        for pos, node in zip(positions, self.nodes):
            node.x, node.y = pos


    def get_memory(self) -> int:
        return get_size(self)

    def get_average_speed(self) -> float:
        """ Return the 5-running mean of the average node speeds """
        return mean(self._average_speeds[-5:]) if len(self._average_speeds) > 0 else np.inf

    def distance_no_cache(self, source: Node, target: Node, cache: bool = False) -> float:
        """ Distance function to use when self.disable_cache = True """
        return self.distance_fn(source.datapoint - target.datapoint)

    def distance(self, source: Node, target: Node, cache: bool = False) -> float:
        """
        Returns the high dimensional distance between two nodes at source and target
        index using self.distance_fn
        """
        pair = frozenset({source, target})
        if pair in self.distances:
            return self.distances[pair]
        distance = self.distance_fn(source.datapoint - target.datapoint)
        if cache:
            self.distances[pair] = distance
        return distance

    def create_knnd_index(self):
        if self.knnd_parameters is not None:
            print("The algorithm will use a k-nearest neighbours graph generated by the k-NN Descent algorithm")
            return pynndescent.NNDescent(self.data, n_neighbors=self.neighbour_set_size + 1,
                                                    **self.knnd_parameters)  # knnd index shows the datapoint itself as
            # the 1st nn - hence neighbour_set_size + 1
        else:
            print("The algorithm will use a k-nearest neighbours graph generated by the k-NN Descent algorithm")
            return pynndescent.NNDescent(self.data, n_neighbors=self.neighbour_set_size + 1)


    def _force(self, current_distance, real_distance, alpha: float = 1) -> float:
        return (current_distance - real_distance) * alpha * self.data_size_factor / current_distance

    def _calculate_velocity(self, source: Node, target: Node, alpha: float = 1,
                            cache_distance: bool = False) -> Tuple[float, float]:
        """
        Calculate the spring force to apply between two nodes i and j
        """
        x, y = self._current_distance(source, target)
        dist = math.hypot(x, y)
        real_dist = self.distance(source, target, cache=cache_distance)
        force = self._force(dist, real_dist, alpha)
        return (x * force, y * force)

    def _current_distance(self, source: Node, target: Node) -> Tuple[float, float]:
        """
        Calculate the current 2d layout distance between two nodes.
        Apply a small non zero random value to remove values of zero
        """
        x = target.x - source.x
        y = target.y - source.y
        # x and y must be non zero
        x = x if x else jiggle()
        y = y if y else jiggle()
        return x, y

    def _set_velocity(self, source: Node, target: Node, alpha: float,
                      cache_distance: bool = False) -> None:
        """
        Calculate the force between two nodes and update the
        velocity of both nodes
        """
        vx, vy = self._calculate_velocity(source, target, alpha=alpha,
                                          cache_distance=cache_distance)
        source.increment_velocity(vx, vy)
        target.increment_velocity(-vx, -vy)

    def _apply_velocities(self) -> None:
        """
        Apply the current velocity of each node to its position
        and reset velocity
        """
        total: float = 0.0
        for node in self.nodes:
            total += math.hypot(node.vx, node.vy)
            node.apply_velocity()
        total /= len(self.nodes)
        self._average_speeds.append(total)
